name: university
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5
  flutter:
    sdk: flutter
  image_picker: ^1.1.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/countries.json
  fonts:
    - family: Rochester
      fonts:
        - asset: fonts/Rochester-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Medium.ttf